services:
  # 1. O Banco de Dados (Coração da integração)
  db:
    image: mysql:8.0
    container_name: hub-db
    environment:
      MYSQL_DATABASE: hub_integrador
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 2. O Redis (Cache para o Diffing)
  redis:
    image: redis:alpine
    container_name: hub-integrador # Nome que você solicitou
    ports:
      - "6379:6379"

  # 3. O Dashboard (Laravel) - Porta 8000
  dashboard:
    build:
      context: ./hub-dashboard
    container_name: hub-dashboard
    ports:
      - "8000:80"
    volumes:
      - ./hub-dashboard:/var/www/html
    depends_on:
      - db
      - redis

  # 4. O Integrador (Node.js) - Porta 3000
  engine:
    build:
      context: ./hub-integrador-fornecedores # Verifique se a pasta tem este nome exato
    container_name: hub-engine
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=hub_integrador
    depends_on:
      - db
      - redis

volumes:
  db_data: